spring:
  timezone: Asia/Ho_Chi_Minh
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://10.1.12.181:3306/fund_management?useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:runsystem-hcm}
    password: ${SPRING_DATASOURCE_PASSWORD:Admi@1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    display-request-duration: true
    persist-authorization: true
    syntax-highlight:
      activated: true
      theme: monokai

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000  # 1 hour 3600000
      refresh-token:
        expiration: 604800000 # a week

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  domain:
    url-v1: http://10.1.12.181:3000
    url-v2: http://localhost:3000
  version: v1
  servlet:
    session:
      cookie:
        http-only: false
        path: /
        secure: true
        same-site: strict
chatops:
  api:
    base-url: ${CHATOPS_URL:https://chat.runsystem.vn}
    token: ${CHATOPS_TOKEN}

create-api:
  base-url: ${CREATE_API_URL:https://api-create.runsystem.info}
  auth-header: ${AUTH_HEADER:ZHhpbnRlcm5hbF9wbDpnb0R4QDIwMjE=}
